theme: minima
title: Nat thoughts
author: Nat Markey

plugins:
 - jekyll-feed
 - jekyll-seo-tag

minima:
  social_links:
    - title: GitHub profile
      icon: github
      url: "https://github.com/n-markey"
  skin: solarized






